### ISSUE TITLE
Problemas con dependency-injection cuando se compilar para producción

### ISSUE THREAD

**Issue by sebas2111mm** [CodelyTV/typescript-ddd-skeleton#50]
Este error viene dado cuando desde cualquier fichero de ruta se hace el import container from '.. /config/dependency-injection' 

`/var/www/vhosts/chatastro.com/develop.api.chatdevelop.com/node_modules/node-dependency-injection/dist/lib/Loader/YamlFileLoader.js:73`
        throw new _ServiceFileNotFoundException["default"](this.filePath);
        ^

Error
    at new ServiceFileNotFoundException (/var/www/vhosts/chatastro.com/develop.api.chatdevelop.com/node_modules/node-dependency-injection/dist/lib/Exception/ServiceFileNotFoundException.js:45:19)
    at YamlFileLoader.load (/var/www/vhosts/chatastro.com/develop.api.chatdevelop.com/node_modules/node-dependency-injection/dist/lib/Loader/YamlFileLoader.js:73:15)
    at Object.<anonymous> (/var/www/vhosts/chatastro.com/develop.api.chatdevelop.com/dist/src/apps/mmc/config/dependency-injection/index.js:7:8)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/var/www/vhosts/chatastro.com/develop.api.chatdevelop.com/dist/src/apps/mmc/routes/authRoute.js:6:32) {
  name: 'ServiceFileNotFoundException'
}
`

**Comment by emilecollin** [comment]
Efectivamente, el error sigue ahí... se agradecería enormemente una actualización del README para poder ejecutarlo

**Comment by JavierCane** [comment]
Error solucionado gracias a las siguientes PRs en la librería de DIC:

* https://github.com/zazoomauro/node-dependency-injection/pull/130
* https://github.com/zazoomauro/node-dependency-injection/pull/134
